export const ROLES = {
  STUDENT: "STUDENT",
  MENTOR: "MENTOR",
  CHIEF_MENTOR: "CHIEF_MENTOR",
  LEADER: "LEADER",
} as const;

export type AppRole = (typeof ROLES)[keyof typeof ROLES];

export const STAFF_ROLES = [ROLES.MENTOR, ROLES.CHIEF_MENTOR, ROLES.LEADER] as const;

export const STUDENT_STATUSES = {
  REGISTERED: "REGISTERED",
  WAITING_FOR_TEAM: "WAITING_FOR_TEAM",
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  COMPLETED: "COMPLETED",
} as const;
