export const ROLES={STUDENT:"STUDENT",MENTOR:"MENTOR",ADMIN:"ADMIN"} as const;
export type AppRole=(typeof ROLES)[keyof typeof ROLES];
export const STUDENT_STATUSES={REGISTERED:"REGISTERED",WAITING_FOR_TEAM:"WAITING_FOR_TEAM",ACTIVE:"ACTIVE",INACTIVE:"INACTIVE",COMPLETED:"COMPLETED"} as const;
