const labels: Record<string, string> = {
  ACTIVE: "Белсенді",
  INACTIVE: "Өшірулі",
  WAITING_FOR_TEAM: "Команда күтілуде",
  REGISTERED: "Тіркелген",
  COMPLETED: "Аяқтаған",
  SUBMITTED: "Жіберілді",
  REVIEWED: "Тексерілді",
  REJECTED: "Қайтарылды",
  APPROVED: "Бекітілді",
  NEW: "Жаңа",
  IN_PROGRESS: "Қаралуда",
  RESOLVED: "Шешілді",
  FULL: "Толық қатысты",
  ATTENDED: "Қатысты",
  ABSENT: "Қатыспады",
  MENTOR: "Ментор",
  STUDENT: "Оқушы",
  LEADER: "Жетекші",
  CHIEF_MENTOR: "Бас ментор",
  ACCOUNT: "Тіркелгі",
  TECHNICAL: "Техникалық мәселе",
  OTHER: "Басқа",
  SCORE: "ҰПАЙ",
  SCORES: "ҰПАЙЛАР",
  ATTENDANCE: "ҚАТЫСУ",
  VIDEO: "БЕЙНЕ",
  TEST: "ТЕСТ",
  TESTS: "ТЕСТТЕР",
  REPORT: "ЕСЕП",
  REPORTS: "ЕСЕПТЕР",
  TASK: "ТАПСЫРМА",
  TASKS: "ТАПСЫРМАЛАР",
  PERFORMANCE: "НӘТИЖЕЛІЛІК",
  CAPACITY: "СЫЙЫМДЫЛЫҚ",
  PROGRESS: "ІЛГЕРІЛЕУ",
  HISTORY: "ТАРИХ",
  NOTIFICATIONS: "ХАБАРЛАНДЫРУЛАР",
  AUDIT: "ЖУРНАЛ",
  SUPPORT: "ҚОЛДАУ",
  SETTINGS: "БАПТАУЛАР",
  MESSAGES: "ХАБАРЛАМАЛАР",
  PRIVATE: "ЖЕКЕ",
  CHAT: "ЧАТ",
  REQUEST: "СҰРАНЫС",
  SUBMISSION: "ТАПСЫРМА ЖҰМЫСЫ",
  DAILY: "КҮНДЕЛІКТІ",
  PENDING: "КҮТУДЕ",
  REVIEW: "ТЕКСЕРУ",
  EMAIL: "ЭЛЕКТРОНДЫҚ ПОШТА",
  PASSWORD: "ҚҰПИЯСӨЗ",
  SEARCH: "ІЗДЕУ",
  FILTER: "СҮЗГІ",
  SAVE: "САҚТАУ",
  CANCEL: "БАС ТАРТУ",
  LOADING: "ЖҮКТЕЛУДЕ",
  ERROR: "ҚАТЕ",
  SUCCESS: "СӘТТІ",
  BACK: "АРТҚА",
  NEXT: "КЕЛЕСІ",
  PREVIOUS: "АЛДЫҢҒЫ",
  SUBMIT: "ЖІБЕРУ",
  EDIT: "ӨҢДЕУ",
  DELETE: "ЖОЮ",
  ADD: "ҚОСУ",
  CREATE: "ЖАСАУ",
  CLOSE: "ЖАБУ",
  OPEN: "АШУ",
  VIEW: "ҚАРАУ",
  DETAILS: "ТОЛЫҒЫРАҚ",
  EXPORT: "ЖҮКТЕУ",
  COMMENT: "ПІКІР",
  SYSTEM: "ЖҮЙЕ",
  team_members: "Команда мүшелері",
  task_submissions: "Тапсырма жұмыстары",
  daily_reports: "Күндік есептер",
  lessons: "Сабақтар",
  tasks: "Тапсырмалар",
  teams: "Командалар",
  profiles: "Пайдаланушылар",
  meet_spaces: "Кездесу кеңістіктері",
  attendance_records: "Қатысу жазбалары",
  score_events: "Ұпай жазбалары",
  support_tickets: "Қолдау өтініштері",
  staff_messages: "Қызметкер хабарламалары",
  UPDATE: "Жаңартылды",
  STATUS_CHANGE: "Мәртебе өзгертілді",
  APPROVE: "Бекітілді",
  REJECT: "Қайтарылды",
  MOVE_STUDENT: "Оқушы ауыстырылды",
  ASSIGN_MENTOR: "Ментор тағайындалды",
  SYNC_MEET: "Кездесу синхрондалды",
  TASK_REQUEST: "ТАПСЫРМА СҰРАНЫСЫ",
};

export function uiLabel(value: unknown): string {
  const raw = String(value ?? "").trim();
  if (!raw) return raw;
  return labels[raw] ?? labels[raw.toUpperCase()] ?? raw;
}
