const SIGNATURES: Record<string, (bytes: Uint8Array) => boolean> = {
  "image/jpeg": (bytes) =>
    bytes.length >= 3 &&
    bytes[0] === 0xff &&
    bytes[1] === 0xd8 &&
    bytes[2] === 0xff,
  "image/png": (bytes) =>
    bytes.length >= 8 &&
    bytes[0] === 0x89 &&
    bytes[1] === 0x50 &&
    bytes[2] === 0x4e &&
    bytes[3] === 0x47 &&
    bytes[4] === 0x0d &&
    bytes[5] === 0x0a &&
    bytes[6] === 0x1a &&
    bytes[7] === 0x0a,
  "image/webp": (bytes) =>
    bytes.length >= 12 &&
    bytes[0] === 0x52 &&
    bytes[1] === 0x49 &&
    bytes[2] === 0x46 &&
    bytes[3] === 0x46 &&
    bytes[8] === 0x57 &&
    bytes[9] === 0x45 &&
    bytes[10] === 0x42 &&
    bytes[11] === 0x50,
  "application/pdf": (bytes) =>
    bytes.length >= 5 &&
    bytes[0] === 0x25 &&
    bytes[1] === 0x50 &&
    bytes[2] === 0x44 &&
    bytes[3] === 0x46 &&
    bytes[4] === 0x2d,
  "application/msword": (bytes) =>
    bytes.length >= 8 &&
    bytes[0] === 0xd0 &&
    bytes[1] === 0xcf &&
    bytes[2] === 0x11 &&
    bytes[3] === 0xe0 &&
    bytes[4] === 0xa1 &&
    bytes[5] === 0xb1 &&
    bytes[6] === 0x1a &&
    bytes[7] === 0xe1,
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document": (bytes) =>
    bytes.length >= 4 &&
    bytes[0] === 0x50 &&
    bytes[1] === 0x4b &&
    bytes[2] === 0x03 &&
    bytes[3] === 0x04,
};

export function hasValidFileSignatureBytes(bytes: Uint8Array, mimeType: string) {
  const validator = SIGNATURES[mimeType];
  return Boolean(validator && validator(bytes));
}

export async function hasValidFileSignature(file: Blob, mimeType: string) {
  const bytes = new Uint8Array(await file.slice(0, 16).arrayBuffer());
  return hasValidFileSignatureBytes(bytes, mimeType);
}

type SignedStorageInspection = {
  ok: boolean;
  sizeBytes: number | null;
  reason: "valid" | "invalid" | "unavailable";
};

/**
 * Validate only the first 16 bytes of an already-uploaded private object.
 * This keeps the completion endpoint from downloading an entire 20 MB file
 * through a serverless function when hundreds of uploads finish together.
 * The URL must be freshly generated by the server's Supabase Storage client.
 */
export async function inspectSignedStorageObject(
  signedUrl: string,
  mimeType: string,
  expectedSizeBytes: number,
  maxBytes: number,
): Promise<SignedStorageInspection> {
  let response: Response | null = null;
  let reader: ReadableStreamDefaultReader<Uint8Array> | null = null;

  try {
    response = await fetch(signedUrl, {
      headers: { Range: "bytes=0-15" },
      cache: "no-store",
      redirect: "error",
    });

    if (response.status !== 206 && response.status !== 200) {
      await response.body?.cancel().catch(() => undefined);
      return { ok: false, sizeBytes: null, reason: "unavailable" };
    }

    let actualSize: number | null = null;
    const contentRange = response.headers.get("content-range");
    if (response.status === 206) {
      const match = contentRange?.match(/^bytes 0-\d+\/(\d+)$/);
      if (match) actualSize = Number(match[1]);
    } else {
      const contentLength = response.headers.get("content-length");
      if (contentLength && /^\d+$/.test(contentLength)) actualSize = Number(contentLength);
    }

    if (
      actualSize === null ||
      !Number.isSafeInteger(actualSize) ||
      actualSize <= 0 ||
      actualSize > maxBytes
    ) {
      await response.body?.cancel().catch(() => undefined);
      return { ok: false, sizeBytes: actualSize, reason: "invalid" };
    }

    reader = response.body?.getReader() ?? null;
    if (!reader) return { ok: false, sizeBytes: actualSize, reason: "unavailable" };

    const collected: Uint8Array[] = [];
    let collectedSize = 0;
    while (collectedSize < 16) {
      const result = await reader.read();
      if (result.done) break;
      collected.push(result.value);
      collectedSize += result.value.byteLength;
    }

    await reader.cancel().catch(() => undefined);
    reader = null;

    const prefix = new Uint8Array(Math.min(16, collectedSize));
    let offset = 0;
    for (const chunk of collected) {
      const remaining = prefix.length - offset;
      if (remaining <= 0) break;
      const slice = chunk.subarray(0, remaining);
      prefix.set(slice, offset);
      offset += slice.byteLength;
    }

    if (
      actualSize !== expectedSizeBytes ||
      prefix.length !== Math.min(16, actualSize) ||
      !hasValidFileSignatureBytes(prefix, mimeType)
    ) {
      return { ok: false, sizeBytes: actualSize, reason: "invalid" };
    }

    return { ok: true, sizeBytes: actualSize, reason: "valid" };
  } catch {
    if (reader) await reader.cancel().catch(() => undefined);
    if (response?.body) await response.body.cancel().catch(() => undefined);
    return { ok: false, sizeBytes: null, reason: "unavailable" };
  }
}

export function isSafeHref(value: string | null | undefined) {
  if (value == null || value.trim() === "") return true;

  const href = value.trim();
  if (href.length > 2000) return false;
  if (/[\u0000-\u001f\u007f]/.test(href)) return false;

  if (href.startsWith("/") && !href.startsWith("//")) return true;

  try {
    const parsed = new URL(href);
    return parsed.protocol === "https:" || parsed.protocol === "http:";
  } catch {
    return false;
  }
}
