"use client";
import { useMemo,useState } from "react";
import { Search } from "lucide-react";
import { StatusPill } from "@/components/ui/ShyraqUI";
import { uiLabel } from "@/lib/ui-labels";
type Log={id:string;actor_id:string;actor_role:string|null;action:string;entity_type:string;entity_id:string|null;metadata:Record<string,unknown>|null;created_at:string};
export function ChiefMentorAuditManager({initialLogs}:{initialLogs:Log[]}){
 const [query,setQuery]=useState("");const [type,setType]=useState("ALL");
 const rows=useMemo(()=>initialLogs.filter(l=>{const q=query.toLowerCase().trim();return(!q||[l.action,l.entity_type,l.actor_role??"",l.entity_id??""].join(" ").toLowerCase().includes(q))&&(type==="ALL"||l.entity_type===type)}),[initialLogs,query,type]);
 const types=[...new Set(initialLogs.map(x=>x.entity_type))];
 return <div><div className="flex flex-col gap-2 border-b border-[#EFE8E1] bg-[#FFFCF9] p-4 sm:flex-row"><div className="relative flex-1"><Search size={13} className="absolute left-3 top-1/2 -translate-y-1/2 text-[#A19890]"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Әрекет, нысан, орындаушы..." className="h-10 w-full rounded-[11px] border border-[#E8E1DA] bg-white pl-9 pr-3 text-[10px] font-semibold outline-none focus:border-[var(--accent)]"/></div><select value={type} onChange={e=>setType(e.target.value)} className="h-10 rounded-[11px] border border-[#E8E1DA] bg-white px-3 text-[10px] font-bold"><option value="ALL">Барлығы</option>{types.map(x=><option key={x} value={x}>{uiLabel(x)}</option>)}</select></div><div className="divide-y divide-[#EFE8E1]">{rows.map(log=><div key={log.id} className="px-5 py-4"><div className="flex flex-wrap items-start gap-3"><div className="min-w-0 flex-1"><p className="text-[10px] font-extrabold text-[#354153]">{uiLabel(log.action)}</p><p className="mt-1 text-[8px] text-[#9A9189]">{uiLabel(log.entity_type)} · {uiLabel(log.actor_role??"SYSTEM")} · {new Date(log.created_at).toLocaleString("kk-KZ")}</p></div><StatusPill tone="neutral">{log.entity_id?log.entity_id.slice(0,8):"SYSTEM"}</StatusPill></div><details className="mt-2 rounded-[11px] bg-[#FFFCF9] px-3 py-2"><summary className="cursor-pointer text-[8px] font-extrabold text-[#7F756D]">Өзгеріске дейінгі және кейінгі деректер</summary><pre className="mt-2 overflow-auto whitespace-pre-wrap text-[8px] leading-4 text-[#655B53]">{JSON.stringify(log.metadata??{},null,2)}</pre></details></div>)}{!rows.length?<div className="p-10 text-center text-xs font-semibold text-[#8B8179]">Журналда сәйкес жазба жоқ.</div>:null}</div><div className="border-t border-[#EFE8E1] bg-[#FFFCF9] px-5 py-3 text-[9px] font-bold text-[#8B8179]">{rows.length} жазба</div></div>;
}
