"use client";

import { useEffect,useState } from "react";

type Question={id:string;marathon_day:number|null;question:string;Өріс кілті:string;Өріс түрі:string;required:boolean;sort_order:number;active:boolean};

export function ReportQuestionManager(){
 const [items,setItems]=useState<Question[]>([]);const [question,setQuestion]=useState("");const [fieldKey,setFieldKey]=useState("");const [day,setDay]=useState("");const [fieldType,setFieldType]=useState("Ұзын мәтін");const [required,setRequired]=useState(true);const [loading,setLoading]=useState(false);const [message,setMessage]=useState("");
 async function load(){const r=await fetch("/api/chief-mentor/report-questions",{cache:"no-store"});const d=await r.json().catch(()=>({}));if(r.ok)setItems(d.questions??[]);}
 useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, []);
 async function create(){setLoading(true);setMessage("");try{const r=await fetch("/api/chief-mentor/report-questions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question,fieldKey,marathonDay:day?Number(day):null,fieldType,required,sortOrder:items.length})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error??"Сұрақ сақталмады.");setQuestion("");setFieldKey("");setDay("");await load();}catch(e){setMessage(e instanceof Error?e.message:"Қате.");}finally{setLoading(false);}}
 async function toggle(item:Question){const r=await fetch("/api/chief-mentor/report-questions",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:item.id,active:!item.active})});if(r.ok)await load();}
 async function remove(id:string){const r=await fetch("/api/chief-mentor/report-questions?id="+id,{method:"DELETE"});if(r.ok)await load();}
 const input="rounded-[11px] border border-[#E8E1DA] bg-white px-3 py-2.5 text-[10px] font-semibold outline-none focus:border-[#FF6F2C]";
 return <section className="rounded-[20px] border border-[#E8E1DA] bg-white p-5"><div><p className="text-[10px] font-extrabold uppercase tracking-[.15em] text-[#FF6F2C]">ЕСЕП СҰРАҚТАРЫ</p><h2 className="mt-1 text-[16px] font-extrabold text-[#172235]">Отчет сұрақтары</h2><p className="mt-1 text-[10px] leading-4 text-[#8B8179]">Барлық күнге ортақ немесе нақты күнге арналған сұрақ қосуға болады.</p></div><div className="mt-4 grid gap-2 md:grid-cols-[1.4fr_1fr_100px_140px_auto]"><input value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Сұрақ мәтіні" className={input}/><input value={fieldKey} onChange={e=>setFieldKey(e.target.value)} placeholder="Өріс кілті" className={input}/><input value={day} onChange={e=>setDay(e.target.value)} type="number" min="1" max="21" placeholder="Күн" className={input}/><select value={fieldType} onChange={e=>setFieldType(e.target.value)} className={input}><option value="Ұзын мәтін">Ұзын мәтін</option><option value="Қысқа мәтін">Қысқа мәтін</option><option value="Сан">Сан</option></select><button disabled={loading} onClick={()=>void create()} className="rounded-[11px] bg-[#FF6F2C] px-4 py-2.5 text-[10px] font-extrabold text-white">{loading?"...":"Сұрақ қосу"}</button></div><label className="mt-3 inline-flex items-center gap-2 text-[10px] font-bold text-[#5B534C]"><input type="checkbox" checked={required} onChange={e=>setRequired(e.target.checked)}/>Міндетті сұрақ</label>{message?<p className="mt-2 text-[9px] font-semibold text-[#B54D2B]">{message}</p>:null}<div className="mt-4 space-y-2">{items.map(item=><div key={item.id} className="flex flex-col gap-2 rounded-[14px] border border-[#E8E1DA] bg-[#FFFCF9] p-3 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><p className="text-[10px] font-extrabold text-[#172235]">{item.question}</p><p className="mt-1 text-[9px] text-[#8B8179]">{item.marathon_day?item.marathon_day+"-күн":"Барлық күн"} · {item.Өріс кілті} · {item.Өріс түрі} · {item.required?"міндетті":"міндетті емес"}</p></div><button onClick={()=>void toggle(item)} className="rounded-[9px] border border-[#E8E1DA] bg-white px-2.5 py-1.5 text-[9px] font-extrabold">{item.active?"Өшіру":"Қосу"}</button><button onClick={()=>void remove(item.id)} className="rounded-[9px] border border-[#E8D3CB] px-2.5 py-1.5 text-[9px] font-extrabold text-[#B54D2B]">Өшіру</button></div>)}</div></section>;
}
