"use client";

import { useState } from "react";
import { Check, Pencil, X } from "lucide-react";
import { PrimaryButton } from "@/components/ui/ShyraqUI";

export type StaffTaskEditProps = {
  task: { id:string; title:string; description:string; instructions:string|null; team_id:string|null; starts_at:string|null; deadline:string|null; points:number; late_points_percent:number; attachment_required:boolean; max_files:number; marathon_day:number|null; task_order:number; active:boolean };
  teams:Array<{id:string;name:string}>;
};

function toDatetimeLocal(value:string|null){if(!value)return ""; const date=new Date(value); if(Number.isNaN(date.getTime()))return ""; const p=(n:number)=>String(n).padStart(2,"0"); return date.getFullYear()+"-"+p(date.getMonth()+1)+"-"+p(date.getDate())+"T"+p(date.getHours())+":"+p(date.getMinutes());}

export function StaffTaskEditForm({task,teams}:StaffTaskEditProps){
  const [editing,setEditing]=useState(false); const [title,setTitle]=useState(task.title); const [description,setDescription]=useState(task.description); const [teamId,setTeamId]=useState(task.team_id??""); const [marathonDay,setMarathonDay]=useState(String(task.marathon_day??"")); const [taskOrder,setTaskOrder]=useState(String(task.task_order??0)); const [startsAt,setStartsAt]=useState(toDatetimeLocal(task.starts_at)); const [deadline,setDeadline]=useState(toDatetimeLocal(task.deadline)); const [points,setPoints]=useState(String(task.points??0)); const [latePointsPercent,setLatePointsPercent]=useState(String(task.late_points_percent??100)); const [maxFiles,setMaxFiles]=useState(String(task.max_files??5)); const [attachmentRequired,setAttachmentRequired]=useState(task.attachment_required); const [active,setActive]=useState(task.active); const [loading,setLoading]=useState(false); const [message,setMessage]=useState("");

  async function save(){setLoading(true);setMessage("");try{const response=await fetch("/api/chief-mentor/tasks/"+task.id,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({title,description,teamId:teamId||null,marathonDay:marathonDay?Number(marathonDay):null,taskOrder:Number(taskOrder||0),startsAt:startsAt?new Date(startsAt).toISOString():null,deadline:deadline?new Date(deadline).toISOString():null,points:Number(points),latePointsPercent:Number(latePointsPercent),maxFiles:Number(maxFiles),attachmentRequired,active})});const data=await response.json().catch(()=>null);if(!response.ok){setMessage(data?.error??"Сақтау сәтсіз аяқталды.");return;}setEditing(false);setMessage("Сақталды.");}finally{setLoading(false);}}
  if(!editing)return <div className="flex flex-col items-end gap-1"><button type="button" onClick={()=>{setMessage("");setEditing(true);}} className="inline-flex min-h-8 items-center gap-1.5 rounded-[10px] border border-[#E8E1DA] bg-white px-3 py-1.5 text-[9px] font-extrabold text-[#4B433C]"><Pencil size={12}/>Өңдеу</button>{message?<span className="text-[8px] font-semibold text-[#7F756D]">{message}</span>:null}</div>;
  const input="rounded-[10px] border border-[#E8E1DA] bg-white px-3 py-2 text-[9px] font-semibold outline-none focus:border-[#FF6F2C]";
  return <div className="w-full rounded-[14px] border border-[#E8E1DA] bg-[#FFFCF9] p-3 sm:w-[520px]"><div className="grid gap-2"><input value={title} onChange={e=>setTitle(e.target.value)} className={input}/><textarea value={description} onChange={e=>setDescription(e.target.value)} rows={2} className={input}/>
    <div className="grid grid-cols-4 gap-2"><input type="number" min="1" max="21" value={marathonDay} onChange={e=>setMarathonDay(e.target.value)} placeholder="Күн" className={input}/><input type="number" min="0" value={taskOrder} onChange={e=>setTaskOrder(e.target.value)} placeholder="Рет" className={input}/><select value={teamId} onChange={e=>setTeamId(e.target.value)} className={input}><option value="">Барлығы</option>{teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><input type="number" min="0" value={points} onChange={e=>setPoints(e.target.value)} placeholder="Ұпай" className={input}/></div>
    <div className="grid grid-cols-3 gap-2"><input type="datetime-local" value={startsAt} onChange={e=>setStartsAt(e.target.value)} className={input}/><input type="datetime-local" value={deadline} onChange={e=>setDeadline(e.target.value)} className={input}/><input type="number" min="0" max="100" value={latePointsPercent} onChange={e=>setLatePointsPercent(e.target.value)} className={input} placeholder="Кеш %"/><input type="number" min="0" max="100" value={latePointsPercent} onChange={e=>setLatePointsPercent(e.target.value)} className={input} placeholder="Late %"/><input type="number" min="1" max="10" value={maxFiles} onChange={e=>setMaxFiles(e.target.value)} className={input} placeholder="Файл лимиті"/></div>
    <div className="flex flex-wrap items-center gap-4 text-[9px] font-bold text-[#5B534C]"><label className="inline-flex items-center gap-2"><input type="checkbox" checked={attachmentRequired} onChange={e=>setAttachmentRequired(e.target.checked)}/>Файл міндетті</label><label className="inline-flex items-center gap-2"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/>ACTIVE</label></div>
    <div className="flex justify-end gap-2"><button type="button" onClick={()=>setEditing(false)} disabled={loading} className="inline-flex min-h-8 items-center gap-1.5 rounded-[10px] border border-[#E8E1DA] bg-white px-3 py-1.5 text-[9px] font-extrabold text-[#6B625B]"><X size={12}/>Бас тарту</button><PrimaryButton type="button" onClick={()=>void save()} disabled={loading} className="!min-h-8 !rounded-[10px] !px-3 !py-1.5 !text-[9px]"><Check size={12}/>{loading?"...":"Сақтау"}</PrimaryButton></div>
    {message?<p className="text-right text-[8px] font-semibold text-[#7F756D]">{message}</p>:null}</div></div>;
}
