"use client";

import { useState } from "react";
import { Loader2, Plus } from "lucide-react";
import { PrimaryButton } from "@/components/ui/ShyraqUI";

export function StaffCreateLessonForm(){
  const [loading,setLoading]=useState(false); const [message,setMessage]=useState(""); const [title,setTitle]=useState(""); const [videoId,setVideoId]=useState(""); const [duration,setDuration]=useState("360"); const [materials,setMaterials]=useState(""); const [marathonDay,setMarathonDay]=useState(""); const [lessonOrder,setLessonOrder]=useState("0"); const [startsAt,setStartsAt]=useState("");
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setLoading(true);setMessage("");try{const response=await fetch("/api/chief-mentor/lessons",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title,kinescopeVideoId:videoId,durationSeconds:Number(duration),marathonDay:marathonDay?Number(marathonDay):null,lessonOrder:Number(lessonOrder||0),startsAt:startsAt?new Date(startsAt).toISOString():null,published:false,materials:materials.split("\n").map(line=>{const [label,...rest]=line.split("|");return {label:label?.trim(),url:rest.join("|").trim(),type:"LINK"};}).filter(item=>item.label&&item.url)})});const data=await response.json().catch(()=>({}));if(!response.ok){setMessage(data.error??"Сабақ сақталмады.");return;}setTitle("");setVideoId("");setDuration("360");setMaterials("");setMarathonDay("");setLessonOrder("0");setStartsAt("");setMessage("Сабақ сәтті қосылды.");}finally{setLoading(false);}}
  const input="rounded-[12px] border border-[#E8E1DA] bg-white px-3 py-2.5 text-[10px] font-semibold outline-none focus:border-[#FF6F2C]";
  return <form onSubmit={submit} className="grid gap-2.5 rounded-[18px] border border-[#E8E1DA] bg-[#FFFCF9] p-4 lg:grid-cols-[1fr_1fr_90px_90px_170px_auto]"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Сабақ атауы" required className={input}/><input value={videoId} onChange={e=>setVideoId(e.target.value)} placeholder="Kinescope video ID" required className={input}/><input value={materials} onChange={e=>setMaterials(e.target.value)} placeholder="Материал: Атауы | https://..." className={input}/><input type="number" min="1" value={duration} onChange={e=>setDuration(e.target.value)} placeholder="Секунд" className={input}/><input type="number" min="1" max="21" value={marathonDay} onChange={e=>setMarathonDay(e.target.value)} placeholder="Күн" className={input}/><input type="datetime-local" value={startsAt} onChange={e=>setStartsAt(e.target.value)} title="Ашылу уақыты" className={input}/><PrimaryButton type="submit" disabled={loading}>{loading?<Loader2 size={13} className="animate-spin"/>:<Plus size={13}/>}Қосу</PrimaryButton>{message?<p className="text-[9px] font-semibold text-[#7F756D] lg:col-span-6">{message}</p>:null}</form>;
}
