"use client";
import { FormEvent, useState } from "react";
import Link from "next/link";
export default function AdminTestsPage(){
 const [message,setMessage]=useState(""); const [loading,setLoading]=useState(false);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setLoading(true);const f=new FormData(event.currentTarget);
 const response=await fetch("/api/admin/tests",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({lessonId:f.get("lessonId"),title:f.get("title"),instructions:f.get("instructions"),maxAttempts:Number(f.get("maxAttempts")||1),passingScore:Number(f.get("passingScore")||0)})});
 const data=await response.json().catch(()=>({}));setMessage(response.ok?"Тест жасалды: "+String(data.test?.id??""):(data.error??"Қате"));setLoading(false);}
 return <main className="min-h-screen bg-[var(--background)] px-6 py-10"><div className="mx-auto max-w-3xl"><Link href="/admin" className="text-sm font-semibold">← Admin</Link><h1 className="mt-6 text-3xl font-semibold">Жаңа тест</h1><p className="mt-2 text-sm text-[var(--muted)]">Алдымен lesson ID дайындаңыз.</p><form onSubmit={submit} className="mt-8 space-y-4 rounded-2xl border border-[var(--border)] bg-white p-6"><input name="lessonId" required placeholder="Lesson UUID" className="w-full rounded-xl border p-3"/><input name="title" required placeholder="Тест атауы" className="w-full rounded-xl border p-3"/><textarea name="instructions" placeholder="Нұсқаулық" rows={3} className="w-full rounded-xl border p-3"/><div className="grid gap-4 sm:grid-cols-2"><input name="maxAttempts" type="number" min="1" defaultValue="1" className="w-full rounded-xl border p-3"/><input name="passingScore" type="number" min="0" defaultValue="0" className="w-full rounded-xl border p-3"/></div>{message?<div className="rounded-xl bg-zinc-50 p-3 text-sm">{message}</div>:null}<button disabled={loading} className="w-full rounded-xl bg-black p-3 font-semibold text-white disabled:opacity-50">{loading?"Сақталуда...":"Жасау"}</button></form></div></main>;
}