"use client";
import { FormEvent, useState } from "react";
import Link from "next/link";
export default function AdminLessonsPage(){
 const [message,setMessage]=useState(""); const [loading,setLoading]=useState(false);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setLoading(true);const f=new FormData(event.currentTarget);
 const response=await fetch("/api/admin/lessons",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:f.get("title"),description:f.get("description"),kinescopeVideoId:f.get("kinescopeVideoId"),durationSeconds:Number(f.get("durationSeconds")||0),requiredWatchPercent:Number(f.get("requiredWatchPercent")||85),sortOrder:Number(f.get("sortOrder")||0),published:f.get("published")==="on"})});
 const data=await response.json().catch(()=>({}));setMessage(response.ok?"Сабақ жасалды.":(data.error??"Қате"));setLoading(false);if(response.ok) event.currentTarget.reset();}
 return <main className="min-h-screen bg-[var(--background)] px-6 py-10"><div className="mx-auto max-w-3xl"><Link href="/admin" className="text-sm font-semibold">← Admin</Link><h1 className="mt-6 text-3xl font-semibold">Жаңа Kinescope сабақ</h1><form onSubmit={submit} className="mt-8 space-y-4 rounded-2xl border border-[var(--border)] bg-white p-6"><input name="title" required placeholder="Сабақ атауы" className="w-full rounded-xl border p-3"/><textarea name="description" placeholder="Сипаттама" rows={3} className="w-full rounded-xl border p-3"/><input name="kinescopeVideoId" required placeholder="Kinescope video ID" className="w-full rounded-xl border p-3"/><div className="grid gap-4 sm:grid-cols-3"><input name="durationSeconds" required type="number" min="1" placeholder="Секунд" className="w-full rounded-xl border p-3"/><input name="requiredWatchPercent" type="number" min="0" max="100" defaultValue="85" className="w-full rounded-xl border p-3"/><input name="sortOrder" type="number" defaultValue="0" className="w-full rounded-xl border p-3"/></div><label className="flex items-center gap-2 text-sm"><input name="published" type="checkbox"/> Бірден жариялау</label>{message?<div className="rounded-xl bg-zinc-50 p-3 text-sm">{message}</div>:null}<button disabled={loading} className="w-full rounded-xl bg-[var(--accent)] p-3 font-semibold text-white disabled:opacity-50">{loading?"Сақталуда...":"Жасау"}</button></form></div></main>;
}